VNC-127 Prevent rebuilding existing KasmVNC images in build script. Enable error checking and update container execution logic

diff --git a/builder/test_build_containers b/builder/test_build_containers
--- a/builder/test_build_containers
+++ b/builder/test_build_containers
@@ -1,9 +1,8 @@
 #!/bin/bash
 
-#set -xe
+#set -e
 
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
 current_dir="$(pwd)"
 
 images_list=()
@@ -18,6 +17,10 @@ for file in "$script_dir"/dockerfile.*.build; do
     filename="$(basename "$file")"
     image_name=$(echo "$filename" | sed -E 's/^(dockerfile\.|Dockerfile\.)(.*)\.build$/\2/')
 
+    if [ -e builder/build/kasmvnc."$image_name".tar.gz ]; then
+        continue
+    fi
+
     echo "Building docker image: $image_name using file: $file"
 
     docker build -f "$file" -t "$image_name" "$current_dir"
@@ -31,20 +34,21 @@ for file in "$script_dir"/dockerfile.*.build; do
 
     echo "Running container from image '$image_name'"
     # Run the container and capture the exit code
-    docker run --rm -it -v "$current_dir":/src "$image_name"
+    docker run -it -v "$current_dir":/src -v "$current_dir/builder/build":/build "$image_name"
     exit_code=$?
 
+    echo "Container for image '$image_name' "
     if [ $exit_code -ne 0 ]; then
-        echo "Container for image '$image_name' exited with error (exit code $exit_code)."
+        echo "exited with error (exit code $exit_code)."
         break
     else
-        echo "Container for image '$image_name' finished successfully."
-        docker rmi "$image_name"
+        echo "finished successfully."
+        images_list+=("$image_name")
     fi
 done
 
 echo "Removing all built docker images..."
 for img in "${images_list[@]}"; do
     echo "Removing docker image: $img"
-    docker rmi "$img"
+    docker rmi -f "$img"
 done
